extensions:
    pim-product-model-add-child-form:
        module: pim/product-model-edit-form/add-child-form

    pim-product-model-add-child-form-header:
        module: pim/product-model-edit-form/add-child-form-header
        parent: pim-product-model-add-child-form
        targetZone: header

    pim-product-model-add-child-form-fields-container:
        module: pim/product-model-edit-form/add-child-form-fields-container
        parent: pim-product-model-add-child-form
        targetZone: fields-container
        config:
            fieldModules:
                akeneo-simple-select-field: pim-product-model-add-child-field-simple-select
                akeneo-multi-select-field: pim-product-model-add-child-field-multi-select
                akeneo-metric-field: pim-product-model-add-child-field-metric
                akeneo-switch-field: pim-product-model-add-child-field-switch
                akeneo-simple-select-reference-data-field: pim-product-model-add-child-field-simple-select-reference-data
                akeneo-multi-select-reference-data-field: pim-product-model-add-child-field-multi-select-reference-data

    pim-product-model-add-child-field-simple-select:
        module: pim/form/common/fields/select
        parent: pim-product-model-add-child-form-fields-container
        targetZone: content
        position: 100
        config:
            fieldName: simple_select

    pim-product-model-add-child-field-multi-select:
        module: pim/form/common/fields/select
        parent: pim-product-model-add-child-form-fields-container
        targetZone: content
        position: 100
        config:
            fieldName: multi_select

    pim-product-model-add-child-field-metric:
        module: pim/form/common/fields/metric
        parent: pim-product-model-add-child-form-fields-container
        targetZone: content
        position: 100
        config:
            fieldName: metric

    pim-product-model-add-child-field-switch:
        module: pim/form/common/fields/boolean
        parent: pim-product-model-add-child-form-fields-container
        targetZone: content
        position: 100
        config:
            fieldName: switch

    pim-product-model-add-child-field-simple-select-reference-data:
        module: pim/form/common/fields/select
        parent: pim-product-model-add-child-form-fields-container
        targetZone: content
        position: 100
        config:
            fieldName: simple_select_reference_data

    pim-product-model-add-child-field-multi-select-reference-data:
        module: pim/form/common/fields/select
        parent: pim-product-model-add-child-form-fields-container
        targetZone: content
        position: 100
        config:
            fieldName: multi_select_reference_data
